package server

const (
	AnsiDisableAlternativeScreenBuffer = "\x1b[?1049l"
	AnsiEnableAlternativeScreenBuffer  = "\x1b[?1049h"
	AnsiEnableMouseTracking            = "\x1b[?1003h"
	AnsiDisableMouseTracking           = "\x1b[?1003l"

	AnsiHideCursor = "\x1b[?25l"
	AnsiShowCursor = "\x1b[?25h"
	AnsiReset      = "\x1b[0m"
	AnsiFgBlack    = "\x1b[30m"
	AnsiBgWhite    = "\x1b[47m"
	AnsiFgWhite    = "\x1b[37m"
	AnsiBgBlack    = "\x1b[40m"
	AnsiFgRed      = "\x1b[31m"
	AnsiBgRed      = "\x1b[41m"
	AnsiFgGreen    = "\x1b[32m"
	AnsiBgGreen    = "\x1b[42m"
	AnsiFgYellow   = "\x1b[33m"
	AnsiBgYellow   = "\x1b[43m"
	AnsiFgBlue     = "\x1b[34m"
	AnsiBgBlue     = "\x1b[44m"
	AnsiFgMagenta  = "\x1b[35m"
	AnsiBgMagenta  = "\x1b[45m"
	AnsiFgCyan     = "\x1b[36m"
	AnsiBgCyan     = "\x1b[46m"

	AnsiBold          = "\x1b[1m"
	AnsiDim           = "\x1b[2m"
	AnsiItalic        = "\x1b[3m"
	AnsiUnderline     = "\x1b[4m"
	AnsiInverse       = "\x1b[7m"
	AnsiHidden        = "\x1b[8m"
	AnsiStrikethrough = "\x1b[9m"
)
